### PR TITLE
fix(#6): upgrade vulnerable dependencies

### PR DESCRIPTION
**Pull request by Ilshidur**
Just upgraded the vulnerable dependencies.
Not sure if the tests are passing, as the `npm test` command fails (no Makefile).

Fixes issue https://github.com/lapwinglabs/x-ray-crawler/issues/6.

### CODE REVIEW

**Comment by jhwohlgemuth** [comment]
@Ilshidur It seems that tests are a [work in progress?](https://github.com/lapwinglabs/x-ray-crawler#test) Also, Travis is not configured (no .travis.yml) and is running with default configuration (in the absence of a configuration file, it assumes a project is a ruby project)

Although, it looks like `node test` might be the current method of testing? Feasibly, you could add a .travis.yml file that identifies this project as a node project and runs `node test` as the test script?

**Comment by Ilshidur** [comment]
I could do that, but I don't get how the `test.js` file works. It doesn't have `describe` nor `assert` statements, however [mocha](https://github.com/mochajs/mocha) is linked in the dependencies (which does not go along with `"test": "make"` in the `"scripts"` section of _package.json_).

**Comment by jhwohlgemuth** [comment]
@Ilshidur it seems to me that `test.js` is just a script to "test run" the software by using it on a familiar site... I would guess that mocha was added toward the goal of adding specs to be run by mocha?

I suppose we could try adding tests (given the choice, my current favorite test tool is Jest 😉)?

**Comment by Ilshidur** [comment]
It would be nice, yes. Using Jest and Travis for CI is a good choice in my opinion.

**Comment by jhwohlgemuth** [comment]
@Ilshidur 
I had a spare minute, so I made a [pull request](https://github.com/lapwinglabs/x-ray-crawler/pull/9)!
Hopefully, it is a welcome contribution 😅

**Comment by matthewmueller** [comment]
@jhwohlgemuth @Ilshidur hey guys, thanks for the PR(s)! Unfortunately, I haven't had time to keep up with this repo. Would you guys like access to help push it forward?

**Comment by jhwohlgemuth** [comment]
@matthewmueller Sounds like fun! Sign me up.

**Comment by Ilshidur** [comment]
All right, I'm in ! :-)

**Comment by matthewmueller** [comment]
thanks guys. i just gave you write access. please share your npm usernames and i'll add you as publishers too :-)

**Comment by Ilshidur** [comment]
My npm username is [ilshidur](https://www.npmjs.com/~ilshidur).
I think will just stay with x-ray-crawler for now :-)

**Comment by jhwohlgemuth** [comment]
My npm username is [jhwohlgemuth](https://github.com/jhwohlgemuth?tab=repositories)

...I **do** use x-ray...and I **am** interested in helping out with the other x-ray repos.

**Comment by matthewmueller** [comment]
awesome, just gave both of you publish rights to this repo, @jhwohlgemuth, i gave you publish + access to x-ray. if you have any questions or need access to more of the repos, let me know. thanks for the help!

**Comment by Ilshidur** [comment]
Thank you @matthewmueller !

I guess we'll merge this PR once https://github.com/lapwinglabs/x-ray-crawler/pull/9 is done and the tests passes.

**Comment by jhwohlgemuth** [comment]
@Ilshidur After a quick rebase this PR should be good to go (I merged #9)

**Comment by Ilshidur** [comment]
Closed in favor of this commit : https://github.com/lapwinglabs/x-ray-crawler/commit/50f171c116e97d204b0aa7c416561d29f87e820c.

**Pull request closed without merging**
